if (EXISTS "${INPUT_DIR}")
    file(GLOB_RECURSE ASSET_FILES RELATIVE "${INPUT_DIR}" "${INPUT_DIR}/*")
    list(SORT ASSET_FILES)
else ()
    set(ASSET_FILES "")
endif ()

file(WRITE "${OUTPUT_CPP}" "")
file(APPEND "${OUTPUT_CPP}" "#include \"embedded_assets.hpp\"\n#include <string_view>\n#include <unordered_map>\n\nnamespace spacestation {\nnamespace {\n")

if (ASSET_FILES)
    set(INDEX 0)
    foreach (FILE_PATH IN LISTS ASSET_FILES)
        set(VAR_NAME "asset_${INDEX}")
        file(READ "${INPUT_DIR}/${FILE_PATH}" CONTENT HEX)
        file(APPEND "${OUTPUT_CPP}" "const unsigned char ${VAR_NAME}[] = {")
        string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," CONTENT_BYTES "${CONTENT}")
        file(APPEND "${OUTPUT_CPP}" "${CONTENT_BYTES}")
        file(APPEND "${OUTPUT_CPP}" "};\n")
        math(EXPR INDEX "${INDEX} + 1")
    endforeach ()

    file(APPEND "${OUTPUT_CPP}" "struct EmbeddedEntry { std::string_view path; const unsigned char* data; size_t size; std::string_view content_type; };\n")
    file(APPEND "${OUTPUT_CPP}" "const EmbeddedEntry kEntries[] = {\n")
    set(INDEX 0)
    foreach (FILE_PATH IN LISTS ASSET_FILES)
        get_filename_component(EXT "${FILE_PATH}" LAST_EXT)
        set(CONTENT_TYPE "application/octet-stream")
        if (EXT STREQUAL ".html")
            set(CONTENT_TYPE "text/html; charset=utf-8")
        elseif (EXT STREQUAL ".js")
            set(CONTENT_TYPE "application/javascript; charset=utf-8")
        elseif (EXT STREQUAL ".css")
            set(CONTENT_TYPE "text/css; charset=utf-8")
        elseif (EXT STREQUAL ".svg")
            set(CONTENT_TYPE "image/svg+xml")
        elseif (EXT STREQUAL ".json")
            set(CONTENT_TYPE "application/json")
        elseif (EXT STREQUAL ".png")
            set(CONTENT_TYPE "image/png")
        elseif (EXT STREQUAL ".ico")
            set(CONTENT_TYPE "image/x-icon")
        endif ()
        file(SIZE "${INPUT_DIR}/${FILE_PATH}" FILE_SIZE)
        file(APPEND "${OUTPUT_CPP}" "    EmbeddedEntry{ \"/${FILE_PATH}\", asset_${INDEX}, ${FILE_SIZE}, \"${CONTENT_TYPE}\" },\n")
        math(EXPR INDEX "${INDEX} + 1")
    endforeach ()
    file(APPEND "${OUTPUT_CPP}" "};\n")
else ()
    file(APPEND "${OUTPUT_CPP}" "const char kFallbackIndex[] = R\"rawliteral(<!doctype html><html lang=\"zh-CN\"><head><meta charset=\"utf-8\"><title>Space Station</title></head><body><h1>Space Station</h1><p>Frontend assets not built yet.</p></body></html>)rawliteral\";\n")
    file(APPEND "${OUTPUT_CPP}" "struct EmbeddedEntry { std::string_view path; const unsigned char* data; size_t size; std::string_view content_type; };\n")
    file(APPEND "${OUTPUT_CPP}" "const EmbeddedEntry kEntries[] = { EmbeddedEntry{ \"/index.html\", reinterpret_cast<const unsigned char*>(kFallbackIndex), sizeof(kFallbackIndex) - 1, \"text/html; charset=utf-8\" } };\n")
endif ()

file(APPEND "${OUTPUT_CPP}" "} // namespace\n\nconst EmbeddedAssetStore kEmbeddedAssets = [] {\n    EmbeddedAssetStore store;\n    for (const auto& entry : kEntries)\n    {\n        store.emplace(std::string(entry.path), EmbeddedAsset{entry.data, entry.size, entry.content_type});\n    }\n    return store;\n}();\n\n} // namespace spacestation\n")
